//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailFailure
    {
        public int MailFailureID { get; set; }
        public System.DateTime Date_of_Failure { get; set; }
        public Nullable<int> spid { get; set; }
        public string EmailFrom { get; set; }
        public string EmailTo { get; set; }
        public string EmailToCC { get; set; }
        public string EmailToBCC { get; set; }
        public string EmailSubject { get; set; }
        public string EmailBody { get; set; }
        public Nullable<int> iMsg { get; set; }
        public Nullable<int> HR { get; set; }
        public string Source_of_Failure { get; set; }
        public string Description_of_Failure { get; set; }
        public string Output_from_Failure { get; set; }
        public string Comment_about_Failure { get; set; }
    }
}
