//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mail
    {
        public int MailId { get; set; }
        public Nullable<System.DateTime> EmailDate { get; set; }
        public string EmailFrom { get; set; }
        public string EmailTo { get; set; }
        public string EmailToCC { get; set; }
        public string EmailToBCC { get; set; }
        public string EmailSubject { get; set; }
        public string EmailBody { get; set; }
    }
}
