//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRI.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MHCC_MRIEntities1 : DbContext
    {
        public MHCC_MRIEntities1()
            : base("name=MHCC_MRIEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AgeCode> AgeCodes { get; set; }
        public DbSet<ClinicalStatu> ClinicalStatus { get; set; }
        public DbSet<County> Counties { get; set; }
        public DbSet<CountyZipCode> CountyZipCodes { get; set; }
        public DbSet<PatientStatu> PatientStatus { get; set; }
        public DbSet<Physician> Physicians { get; set; }
        public DbSet<PhysicianLicensure> PhysicianLicensures { get; set; }
        public DbSet<PhysicianPrefixCode> PhysicianPrefixCodes { get; set; }
        public DbSet<PhysicianSite> PhysicianSites { get; set; }
        public DbSet<PhysicianSpecialty> PhysicianSpecialties { get; set; }
        public DbSet<Scan> Scans { get; set; }
        public DbSet<ScanComplete> ScanCompletes { get; set; }
        public DbSet<ScanContrast> ScanContrasts { get; set; }
        public DbSet<ScanRegion> ScanRegions { get; set; }
        public DbSet<ScanResult> ScanResults { get; set; }
        public DbSet<Sedation> Sedations { get; set; }
        public DbSet<Sex> Sexes { get; set; }
        public DbSet<Site> Sites { get; set; }
        public DbSet<SourceOfPayment> SourceOfPayments { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<OraclePatientExport> OraclePatientExports { get; set; }
        public DbSet<vwPhysicianSpecialtyList> vwPhysicianSpecialtyLists { get; set; }
        public DbSet<vwPhysician> vwPhysicians { get; set; }
    }
}
