//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OraclePatientExport
    {
        public int OraclePatientExportId { get; set; }
        public System.DateTime DateOfScan { get; set; }
        public string PatientName { get; set; }
        public string AccountNumber { get; set; }
        public string MedicalRecordNumber { get; set; }
        public string DescriptionOfScan { get; set; }
        public Nullable<int> Sex { get; set; }
        public string ZipCode { get; set; }
        public Nullable<int> PatientStatus { get; set; }
        public Nullable<System.DateTime> PatientDOB { get; set; }
        public Nullable<int> AgeOfPatient { get; set; }
        public string AgeCode { get; set; }
        public string MainSiteCode { get; set; }
        public string County { get; set; }
    }
}
