//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientStatu
    {
        public PatientStatu()
        {
            this.Scans = new HashSet<Scan>();
        }
    
        public int PatientStatusId { get; set; }
        public string PatientStatusCode { get; set; }
        public string PatientStatusDescription { get; set; }
    
        public virtual ICollection<Scan> Scans { get; set; }
    }
}
