//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicianSite
    {
        public PhysicianSite()
        {
            this.Scans = new HashSet<Scan>();
        }
    
        public int PhysicianSiteId { get; set; }
        public int PhysicianId { get; set; }
        public int SiteId { get; set; }
        public bool Active { get; set; }
    
        public virtual Physician Physician { get; set; }
        public virtual Site Site { get; set; }
        public virtual ICollection<Scan> Scans { get; set; }
    }
}
