//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Physician
    {
        public Physician()
        {
            this.PhysicianSites = new HashSet<PhysicianSite>();
        }
    
        public int PhysicianId { get; set; }
        public int PhysicianSpecialtyId { get; set; }
        public string LicenseNumber { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Suffix { get; set; }
        public string AddressNumber { get; set; }
        public string AddressNumberSuffix { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressSuffixType { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public int StateId { get; set; }
        public string ZipCode { get; set; }
        public string ZipCodeExtension { get; set; }
        public int PhysicianLicensureId { get; set; }
        public bool Active { get; set; }
    
        public virtual PhysicianLicensure PhysicianLicensure { get; set; }
        public virtual PhysicianSpecialty PhysicianSpecialty { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<PhysicianSite> PhysicianSites { get; set; }
    }
}
