//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicianLicensure
    {
        public PhysicianLicensure()
        {
            this.Physicians = new HashSet<Physician>();
        }
    
        public int PhysicianLicensureId { get; set; }
        public string PhysicianLicensureCode { get; set; }
        public string PhysicianLicensureDescription { get; set; }
    
        public virtual ICollection<Physician> Physicians { get; set; }
    }
}
