//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScanComplete
    {
        public ScanComplete()
        {
            this.ScanResults = new HashSet<ScanResult>();
        }
    
        public int ScanCompleteId { get; set; }
        public string ScanCompleteCode { get; set; }
        public string ScanCompleteDescription { get; set; }
    
        public virtual ICollection<ScanResult> ScanResults { get; set; }
    }
}
