//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScanResult
    {
        public int ScanResultId { get; set; }
        public int ScanId { get; set; }
        public Nullable<int> ScanRegionId { get; set; }
        public Nullable<int> SedationId { get; set; }
        public Nullable<int> ScanContrastId { get; set; }
        public Nullable<int> ScanCompleteId { get; set; }
    
        public virtual Scan Scan { get; set; }
        public virtual ScanComplete ScanComplete { get; set; }
        public virtual ScanContrast ScanContrast { get; set; }
        public virtual ScanRegion ScanRegion { get; set; }
        public virtual Sedation Sedation { get; set; }
    }
}
