//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sex
    {
        public Sex()
        {
            this.Scans = new HashSet<Scan>();
        }
    
        public int SexId { get; set; }
        public int SexCode { get; set; }
        public string SexDescription { get; set; }
    
        public virtual ICollection<Scan> Scans { get; set; }
    }
}
