//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        public Site()
        {
            this.PhysicianSites = new HashSet<PhysicianSite>();
            this.Scans = new HashSet<Scan>();
        }
    
        public int SiteId { get; set; }
        public string SiteCode { get; set; }
        public string SiteName { get; set; }
        public int StateId { get; set; }
        public string ServiceIdNumber { get; set; }
        public string FromEmailAddress { get; set; }
        public string ToEmailAddress { get; set; }
        public string EmailSubject { get; set; }
        public string ADGroupAdmin { get; set; }
        public string ADGroupUserEntry { get; set; }
        public bool Active { get; set; }
        public string ADGroupModifyEntry { get; set; }
        public string ADGroupSubmissionReport { get; set; }
        public string ADGroupReport { get; set; }
    
        public virtual ICollection<PhysicianSite> PhysicianSites { get; set; }
        public virtual ICollection<Scan> Scans { get; set; }
        public virtual State State { get; set; }
    }
}
