//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceOfPayment
    {
        public SourceOfPayment()
        {
            this.Scans = new HashSet<Scan>();
        }
    
        public int SourceOfPaymentId { get; set; }
        public string SourceCode { get; set; }
        public string SourceName { get; set; }
        public int StateId { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Scan> Scans { get; set; }
        public virtual State State { get; set; }
    }
}
