//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public State()
        {
            this.Counties = new HashSet<County>();
            this.Physicians = new HashSet<Physician>();
            this.PhysicianPrefixCodes = new HashSet<PhysicianPrefixCode>();
            this.Sites = new HashSet<Site>();
            this.SourceOfPayments = new HashSet<SourceOfPayment>();
        }
    
        public int StateId { get; set; }
        public string StateCode { get; set; }
        public string StateName { get; set; }
    
        public virtual ICollection<County> Counties { get; set; }
        public virtual ICollection<Physician> Physicians { get; set; }
        public virtual ICollection<PhysicianPrefixCode> PhysicianPrefixCodes { get; set; }
        public virtual ICollection<Site> Sites { get; set; }
        public virtual ICollection<SourceOfPayment> SourceOfPayments { get; set; }
    }
}
